require 'thor'
require 'colorize'
require 'power-build/constructor'

module PowerBuild
  class Base < Thor
    desc "build, b", "Generates a static site. Old files will be overwritten."
    map %w[b] => :build
    default_task :build
    def build 
      Constructor.copy_assets
      Constructor.render_index
      puts "Done!"
    end

    desc "init, i", "Start with a config file. Continue with 'power build' if you have nothing to change."
    map %w[i] => :init
    def init
      Constructor.build_config
    end

    desc "delete, d", "Remove all files generated by Power Build"
    map %w[d] => :clean
    def delete
      Constructor.remove_config
    end

    desc "config, open, o", "Open the config file for you if you're this lazy"
    map %w[open, o] => :config
    def config
      Constructor.open_config
    end

    map %w[--version -v] => :__print_version
    desc "--version, -v", "show version"
    def __print_version
      puts PowerBuild::VERSION
    end
  end
end
